[project]
name = "rest-is-hist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "ipdb>=0.13.13",
    "requests>=2.32.3",
]
